language: generic
env:
  global:
    - IDE_VERSION=1.8.13
    - BOARD="esp8266:esp8266:generic:xtal=80,eesz=4M3M,ip=lm2f,exception=disabled,FlashMode=qio,FlashFreq=80"
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - sudo mv arduino-$IDE_VERSION ~/arduino-ide
  - export PATH=~/arduino-ide:$PATH
  - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
  - arduino --install-library PubSubClient,PageBuilder,PseudoPWM,ESP8266Ping_source
install:
  - mkdir -p ~/Arduino/libraries
  - ln -s $PWD ~/Arduino/libraries/.
script:
  - arduino --verify --board $BOARD $PWD/ESPShaker/ESPShaker.ino
