language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    wget https://github.com/Hieromon/PageBuilder/archive/master.zip -O /tmp/PageBuilder_source.zip
    unzip /tmp/PageBuilder_source.zip -d /tmp
    wget https://github.com/Hieromon/PseudoPWM/archive/master.zip -O /tmp/PseudoPWM_source.zip
    unzip /tmp/PseudoPWM_source.zip -d /tmp

script:
    - platformio ci --lib="." --lib="/tmp/PageBuilder-master" --lib="/tmp/PseudoPWM-master" --board=nodemcuv2
