language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    global:
        - PLATFORMIO_CI_SRC=./ESPShaker
        - build_flags=-D NO_EXTRA_4K_HEAP

install:
    - pip install -U platformio

    - wget https://github.com/Hieromon/PageBuilder/archive/master.zip -O /tmp/PageBuilder_source.zip
    - unzip /tmp/PageBuilder_source.zip -d /tmp

    - wget https://github.com/Hieromon/PseudoPWM/archive/master.zip -O /tmp/PseudoPWM_source.zip
    - unzip /tmp/PseudoPWM_source.zip -d /tmp

    - wget https://github.com/knolleary/pubsubclient/archive/master.zip -O /tmp/pubsubclient_source.zip
    - unzip /tmp/pubsubclient_source.zip -d /tmp

    - wget https://github.com/dancol90/ESP8266Ping/archive/master.zip -O /tmp/ESP8266Ping_source.zip
    - unzip /tmp/ESP8266Ping_source.zip -d /tmp

script:
    - platformio ci --lib="." --lib="/tmp/PageBuilder-master" --lib="/tmp/PseudoPWM-master" --lib="/tmp/pubsubclient-master" --lib="/tmp/ESP8266Ping-master" --board=nodemcuv2
